from .queries import (
    GET_ALL_SESSIONS,
    SESSIONS_PER_USER,
    TIME_TO_ORDER_CONFIRMATION,
    CALCULATE_COORDINATES_CHANGE,
    ORDER_PLACED_IF_CUSTOMER_CHANGED_LOCATION,
    ORDER_PLACED_PER_VISITOR_ID,
)
